language: node_js
node_js:
- lts/*
script:
- npm run build
deploy:
  edge: true
  provider: pages:git
  deploy_key: id_rsa
  local_dir: public
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_ada7a79f999c_key -iv $encrypted_ada7a79f999c_iv
  -in id_rsa.enc -out id_rsa -d
